// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package layout

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Footer() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"footer\"><div style=\"display: inline-block;\"><a href=\"https://github.com/tidurak/debilbot\" target=\"_blank\" rel=\"noopener\" style=\"margin-right:10px;\">GitHub Репопидорий</a> <a href=\"https://discord.com/oauth2/authorize?client_id=699912361481470032&permissions=8&integration_type=0&scope=bot\" target=\"_blank\" rel=\"noopener\" style=\"margin-right:10px;\">Добавить бота</a> <a href=\"https://discord.com/invite/4dEmQjt\" target=\"_blank\" rel=\"noopener\" style=\"margin-right:10px;\">Discord Сервак с дебилботом и долбаёбами</a> <a href=\"https://t.me/noname_tapok\" target=\"_blank\" rel=\"noopener\" style=\"margin-right:10px;\">Телеграм для связи</a></div><p><i>govnoed.de</i> - Первый русскоязычный сайт для программистов-говноедов.</p><p>© gdisclaimer. Все права сходили нахуй.</p></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
